typo

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -51,236 +51,236 @@ on:
   pull_request:
 
 jobs:
-  terraform-development:
-    name: 'Development'
-    runs-on: ubuntu-latest
-    environment: development
-    env:
-      TF_IN_AUTOMATION: true
-      TF_WORKSPACE: fancy-app-development
+#   terraform-development:
+#     name: 'Development'
+#     runs-on: ubuntu-latest
+#     environment: development
+#     env:
+#       TF_IN_AUTOMATION: true
+#       TF_WORKSPACE: fancy-app-development
 
-    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-    defaults:
-      run:
-        shell: bash
+#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+#     defaults:
+#       run:
+#         shell: bash
 
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
+#     steps:
+#     # Checkout the repository to the GitHub Actions runner
+#     - name: Checkout
+#       uses: actions/checkout@v3
 
-    - uses: actions/cache@v2
-      name: Cache plugin dir
-      with:
-        path: ~/.tflint.d/plugins
-        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
+#     - uses: actions/cache@v2
+#       name: Cache plugin dir
+#       with:
+#         path: ~/.tflint.d/plugins
+#         key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
 
-    - uses: terraform-linters/setup-tflint@v2
-      name: Setup TFLint
-      with:
-        tflint_version: latest
+#     - uses: terraform-linters/setup-tflint@v2
+#       name: Setup TFLint
+#       with:
+#         tflint_version: latest
 
-    - name: Show version
-      run: tflint --version
+#     - name: Show version
+#       run: tflint --version
 
-    - name: Init TFLint
-      run: tflint --init
+#     - name: Init TFLint
+#       run: tflint --init
 
-    - name: Run TFLint
-      run: tflint -f compact
+#     - name: Run TFLint
+#       run: tflint -f compact
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-        terraform_version: 1.2.8
+#     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+#     - name: Setup Terraform
+#       uses: hashicorp/setup-terraform@v2
+#       with:
+#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#         terraform_version: 1.2.8
 
-    # Checks that all Terraform configuration files adhere to a canonical format
-    - name: Terraform Format
-      id: fmt
-      run: terraform fmt -check
-      continue-on-error: true
+#     # Checks that all Terraform configuration files adhere to a canonical format
+#     - name: Terraform Format
+#       id: fmt
+#       run: terraform fmt -check
+#       continue-on-error: true
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      id: init
-      run: |
-        terraform init -input=false
+#     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+#     - name: Terraform Init
+#       id: init
+#       run: |
+#         terraform init -input=false
 
-    # Validate that all Terraform configuration files are syntactically valid and internally consistent
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
+#     # Validate that all Terraform configuration files are syntactically valid and internally consistent
+#     - name: Terraform Validate
+#       id: validate
+#       run: terraform validate -no-color
 
-    # Generates an execution plan for Terraform
-    - name: Terraform Plan
-      id: plan
-      if: github.event_name == 'pull_request'
-      run: terraform plan -no-color
-      continue-on-error: true
-      # This step will continue even when it errors. This allows the next step to display the plan error message even if this step fails.
+#     # Generates an execution plan for Terraform
+#     - name: Terraform Plan
+#       id: plan
+#       if: github.event_name == 'pull_request'
+#       run: terraform plan -no-color
+#       continue-on-error: true
+#       # This step will continue even when it errors. This allows the next step to display the plan error message even if this step fails.
 
-    - name: Update Pull Request
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#     - name: Update Pull Request
+#       uses: actions/github-script@v6
+#       if: github.event_name == 'pull_request'
+#       env:
+#         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#       with:
+#         github-token: ${{ secrets.GITHUB_TOKEN }}
+#         script: |
+#           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-          <details><summary>Show Plan</summary>
+#           <details><summary>Show Plan</summary>
 
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
+#           \`\`\`\n
+#           ${process.env.PLAN}
+#           \`\`\`
 
-          </details>
+#           </details>
 
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+#           github.rest.issues.createComment({
+#             issue_number: context.issue.number,
+#             owner: context.repo.owner,
+#             repo: context.repo.repo,
+#             body: output
+#           })
 
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform Plan Status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
 
-      # On push to main, build or change infrastructure according to Terraform configuration files
-      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      id: apply
-      run: terraform apply -auto-approve
+#       # On push to main, build or change infrastructure according to Terraform configuration files
+#       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+#     - name: Terraform Apply
+#       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#       id: apply
+#       run: terraform apply -auto-approve
 
-    # - name: Get Cost Estimate ID
-    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-    #   run: |
-    #      '${{ steps.apply.outputs.stdout || steps.apply.outputs.stderr }}' | grep -E 'run-[a-zA-Z0-9]+'
+#     # - name: Get Cost Estimate ID
+#     #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#     #   run: |
+#     #      '${{ steps.apply.outputs.stdout || steps.apply.outputs.stderr }}' | grep -E 'run-[a-zA-Z0-9]+'
 
-# Tip: In a production environment, consider adding "Require status checks to pass before merging"
-# as a Branch Protection rule. This adds another layer of protection, ensuring that this workflow
-# successfully completes before changes are merged into main.
+# # Tip: In a production environment, consider adding "Require status checks to pass before merging"
+# # as a Branch Protection rule. This adds another layer of protection, ensuring that this workflow
+# # successfully completes before changes are merged into main.
 
-  terraform-staging:
-    name: 'Staging'
-    needs: terraform-development
-    runs-on: ubuntu-latest
-    environment: staging
-    env:
-      TF_IN_AUTOMATION: true
-      TF_WORKSPACE: fancy-app-staging
+#   terraform-staging:
+#     name: 'Staging'
+#     needs: terraform-development
+#     runs-on: ubuntu-latest
+#     environment: staging
+#     env:
+#       TF_IN_AUTOMATION: true
+#       TF_WORKSPACE: fancy-app-staging
 
-    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-    defaults:
-      run:
-        shell: bash
+#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+#     defaults:
+#       run:
+#         shell: bash
 
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
+#     steps:
+#     # Checkout the repository to the GitHub Actions runner
+#     - name: Checkout
+#       uses: actions/checkout@v3
 
-    - uses: actions/cache@v2
-      name: Cache plugin dir
-      with:
-        path: ~/.tflint.d/plugins
-        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
+#     - uses: actions/cache@v2
+#       name: Cache plugin dir
+#       with:
+#         path: ~/.tflint.d/plugins
+#         key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
 
-    - uses: terraform-linters/setup-tflint@v2
-      name: Setup TFLint
-      with:
-        tflint_version: latest
+#     - uses: terraform-linters/setup-tflint@v2
+#       name: Setup TFLint
+#       with:
+#         tflint_version: latest
 
-    - name: Show version
-      run: tflint --version
+#     - name: Show version
+#       run: tflint --version
 
-    - name: Init TFLint
-      run: tflint --init
+#     - name: Init TFLint
+#       run: tflint --init
 
-    - name: Run TFLint
-      run: tflint -f compact
+#     - name: Run TFLint
+#       run: tflint -f compact
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-        terraform_version: 1.2.8
+#     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+#     - name: Setup Terraform
+#       uses: hashicorp/setup-terraform@v2
+#       with:
+#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#         terraform_version: 1.2.8
 
-    # Checks that all Terraform configuration files adhere to a canonical format
-    - name: Terraform Format
-      id: fmt
-      run: terraform fmt -check
-      continue-on-error: true
+#     # Checks that all Terraform configuration files adhere to a canonical format
+#     - name: Terraform Format
+#       id: fmt
+#       run: terraform fmt -check
+#       continue-on-error: true
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      id: init
-      run: |
-        terraform init -input=false
+#     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+#     - name: Terraform Init
+#       id: init
+#       run: |
+#         terraform init -input=false
 
-    # Validate that all Terraform configuration files are syntactically valid and internally consistent
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
+#     # Validate that all Terraform configuration files are syntactically valid and internally consistent
+#     - name: Terraform Validate
+#       id: validate
+#       run: terraform validate -no-color
 
-    # Generates an execution plan for Terraform
-    - name: Terraform Plan
-      id: plan
-      if: github.event_name == 'pull_request'
-      run: terraform plan -no-color
-      continue-on-error: true
-      # This step will continue even when it errors. This allows the next step to display the plan error message even if this step fails.
+#     # Generates an execution plan for Terraform
+#     - name: Terraform Plan
+#       id: plan
+#       if: github.event_name == 'pull_request'
+#       run: terraform plan -no-color
+#       continue-on-error: true
+#       # This step will continue even when it errors. This allows the next step to display the plan error message even if this step fails.
 
-    - name: Update Pull Request
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#     - name: Update Pull Request
+#       uses: actions/github-script@v6
+#       if: github.event_name == 'pull_request'
+#       env:
+#         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#       with:
+#         github-token: ${{ secrets.GITHUB_TOKEN }}
+#         script: |
+#           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-          <details><summary>Show Plan</summary>
+#           <details><summary>Show Plan</summary>
 
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
+#           \`\`\`\n
+#           ${process.env.PLAN}
+#           \`\`\`
 
-          </details>
+#           </details>
 
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+#           github.rest.issues.createComment({
+#             issue_number: context.issue.number,
+#             owner: context.repo.owner,
+#             repo: context.repo.repo,
+#             body: output
+#           })
 
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform Plan Status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
 
-      # On push to main, build or change infrastructure according to Terraform configuration files
-      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: terraform apply -auto-approve
+#       # On push to main, build or change infrastructure according to Terraform configuration files
+#       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+#     - name: Terraform Apply
+#       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#       run: terraform apply -auto-approve
 
 # Tip: In a production environment, consider adding "Require status checks to pass before merging"
 # as a Branch Protection rule. This adds another layer of protection, ensuring that this workflow
@@ -351,5 +351,5 @@ jobs:
     - name: Get cost estimate
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: |
-        echo "${{ steps.tfe-run.outputs.run-url }}"
+        echo "${{ steps.tfe-apply.outputs.run-url }}"
         curl -X POST https://app.terraform.io/api/v2/runs/RUN_ID -H "Content-Type: application/vnd.api+json" -H "Accept: application/vnd.api+json" -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}"
